### ISSUE TITLE
VSCode `.css.ts` module resolution error

### ISSUE THREAD

**Issue by Vynlar** [seek-oss/vanilla-extract#56] opened 2021-04-28 17:37 UTC
I have successfully set up `vanilla-extract` using webpack and my sample app works in the browser! 🎉 

---

However, my issue is that VSCode fails to correctly resolve `.css.ts` imports and therefore I lose the power of autocomplete/inline type checking!

The specific problem is this: 
![CleanShot 2021-04-28 at 12 26 33](https://user-images.githubusercontent.com/920212/116446859-fea97080-a81c-11eb-8c3a-a961a0f8b83d.png)
```
An import path cannot end with a '.ts' extension. Consider importing './atoms.css.js' instead.
```

The typescript language server in VSCode doesn't like it when imports end with `.ts` and there doesn't appear to be a way to fix this. 

> This is a long-standing issue (specifically affecting deno users) but appears to affect `vanilla-extract` as well. See https://github.com/Microsoft/TypeScript/issues/27481

---

If I import `./atoms.css` (or `./atoms.css.js`) then *VSCode correctly picks up the types*; however, webpack no longer resolves the file correctly, causing the build to break.
![CleanShot 2021-04-28 at 12 28 38](https://user-images.githubusercontent.com/920212/116447159-4af4b080-a81d-11eb-8a01-ab1ac4cf1a09.png)

How can I reconcile these two worlds to make them both happy at the same time?

**Comment by markdalgleish** [comment] 2021-04-28 22:48
Do you have `.ts` in your extensions list? https://webpack.js.org/configuration/resolve/#resolveextensions

**Comment by mattcompiles** [comment] 2021-05-05 23:12
I don't think the issue is on our end here. Closing until a reproduction is provided.

**Closed by mattcompiles** 2021-05-05 23:12 UTC

**Comment by twoKilo** [comment] 2022-11-08 10:36
got the same error, thrown by rollup-plugin-typescript2

**Comment by xxKeefer** [comment] 2022-11-22 11:21
If there is a fix for this please let me know. I suffer from this as well
