### ISSUE TITLE
Monorepo vite project get 404 error

### ISSUE THREAD

**Issue by Tatamethues** [seek-oss/vanilla-extract#559] opened 2022-01-08 15:55 UTC
I'm facing the [same issue](https://github.com/seek-oss/vanilla-extract/issues/320#issue-979131910)
```
GET http://localhost:3000/@id/packages/ui/src/Button/button.css.ts$$$dashboard.vanilla.js net::ERR_ABORTED 404 (Not Found)`.
```
the app is using turborepo. All versions are latest.
app's viteconfig
```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin';
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(),vanillaExtractPlugin()]
})
```
package.json
```
{
  "dependencies": {
    "ui": "*",
    "@vanilla-extract/css": "^1.6.8",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "eslint-config": "*",
    "@types/react": "^17.0.33",
    "@types/react-dom": "^17.0.10",
    "@vanilla-extract/vite-plugin": "^3.1.2",
    "@vitejs/plugin-react": "^1.0.7",
    "eslint": "^8.5.0",
    "tsconfig": "*",
    "typescript": "^4.4.4",
    "vite": "^2.7.2"
  }
}
</div>

**Comment by andrejilderda** [comment] 2022-01-15 19:14
I just ran into the same issue with a monorepo setup, which I managed to solve by changing the folder structure from:

- packages
  - components
    - button (has imports from modules in src)
- src

To:
- packages
  - components
    - button
  - src

I'm not sure why this fixes the issue, but maybe it helps!

**Comment by Tatamethues** [comment] 2022-01-17 01:21
I'm using turborepo's default folder structure.
- apps
  - app1
    - src
- packages 
  - library1
    - src
Since I cant fix the problem, I decided not to move to vite and turborepo from nx.

**Comment by BJvdA** [comment] 2022-01-18 13:41
I ran into the same issue and tried to figure out the cause in this repro:
[https://github.com/BJvdA/vite-vanilla-extract-nested-bug](https://github.com/BJvdA/vite-vanilla-extract-nested-bug).
It seems like it's indeed caused by the folder structure, when a project is setup like:

- apps
  - nested-site
- packages
  - components
- site 

It will work normally in `site`, but break in `nested-site`. The vanilla-extract vite plugin still transforms the code of `components`, but vite serves it as if it wasn't transformed. Perhaps it's not allowed as a security mechanism because it's relative path is further up in the tree (`../..` vs `..`)

**Comment by Tatamethues** [comment] 2022-01-30 16:27
@BJvdA Did you find a solution？

**Comment by BJvdA** [comment] 2022-01-31 09:31
@Tatamethues Couldn't fix it, so I went with the workaround of moving nested package folders to the root of the project

**Comment by florianmatz** [comment] 2022-02-17 22:58
Experiencing the same issue, also with turborepo, better said (npm) workspaces.

What worked for me is indeed putting the site instead of the app folder into the packages next to my ui-kit. 

Like:

- apps
   - site -> not working 
- packages 
   - ui-kit 
   - site -> working 
   
   
ui-kit is a dependency in the sites package.json:

„dependencies“: {
  „ui-kit“: „*“
}

Still, it feels not good, starting a repo with breaking conventions.

It seems to me, [the described fix](https://github.com/seek-oss/vanilla-extract/issues/320#issue-979131910) only fixed it ‚one level‘ higher in the folder hierarchy?

 @markdalgleish Could you provide some assistance?

**Comment by edenstrom** [comment] 2022-02-21 08:59
Same issue here with `yarn workspaces`. 

```
apps/
  vite-app
packages/
  ui
```

All imports starting with `@fs` is working and all starting with `@id` referencing the ui package fails.

Moving our apps from the app directory is a no go.

I'll see if I can debug it and find some more information about it.

**Comment by mattcompiles** [comment] 2022-03-21 11:27
This looks to be caused from `..` being invalid in a URL. Hopefully fixed in the next patch.

**Comment by edenstrom** [comment] 2022-03-21 11:54
> This looks to be caused from `..` being invalid in a URL. Hopefully fixed in the next patch.

Tried it locally and worked like a charm! 👌 Thanks!

(Copy-pasted the changed lines into `dist/vanilla-extract-vite-plugin.cjs.dev.js`)

**Closed** 2022-03-21 21:45 UTC

**Comment by florianmatz** [comment] 2022-03-22 12:39
@mattcompiles Perfect! Thank you :)
